---
- name: test the authentication 
  hosts: routers

  tasks:
    - name: show the username
      debug:
        msg: "{{ansible_user}}"

    - name: get Facts
      debug:
        msg: "the facts are {{ansible_facts}}"

    - name: excute show command
      ios_command:
        commands:
#          - show run
          - show ip interface brief

    - name: get facts
      ios_facts:
        gather_subset: all
      register: inters

    - name: show interfaces 
      debug:
        var: inters

    - name: the interfaces ip addrsses are
      debug:
        msg: "{{inters['ansible_facts']['ansible_net_all_ipv4_addresses']}}"
