---
- name: ios interface
  hosts: sw
  tasks:

    - name: Create VLANs on switch
      cisco.ios.ios_config:
        lines:
        - vlan 15
        - name hocine
        - vlan 25
        - name kebbabi       
      register: Vlan  

    # - name: config from external file
    #   ios_config:
    #     diff_against: startup

    - debug:
        var: Vlan.commands
      